@baseUrl = http://localhost:3333/api/v1
@projectId = {{createUser.response.body.id}}

### Create Project
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matheus Moreira Militão",
  "email": "eriks@gmail.com",
  "password": "12345678"
}

### List Projects
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZEVtcHJlc2EiOiJhZjhmYjIzNS1lYThmLTQ3MGMtYThmYy1hNzFkYjg3ZDgzNjciLCJpZFVzZXIiOiI4YzczODNjZi1mNTcwLTQ0NzEtODI1Ny1mZDIxOGUxZGQ3YTUiLCJpYXQiOjE3NjM3NjYwNjIsImV4cCI6MTc2NjM1ODA2Mn0.CUuKO1x53HB0VoBtRudDhn0zByho8fjtLuOC8v6b0XY

### Get Project By ID
GET {{baseUrl}}/projects/{{projectId}}

### Delete Project
DELETE {{baseUrl}}/projects/{{projectId}}


### auth
POST {{baseUrl}}/users/auth
Content-Type: application/json

{
  "email": "matheus@gmail.com",
  "password": "12345678"
}
