@baseUrl = http://localhost:3333/api/v1
@authToken = paste-your-auth-token-here

### Create user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Example User",
  "email": "user@example.com",
  "password": "12345678"
}

### Authenticate user
POST {{baseUrl}}/users/auth
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "12345678"
}

### List users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}
