@baseUrl = https://telemetry-telemetry-api.qltz9y.easypanel.host/api/v1
@projectId = {{createUser.response.body.id}}

### Create Project
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matheus Moreira Militão",
  "email": "matheus@gmail.com",
  "password": "12345678"
}

### List Projects
GET {{baseUrl}}/projects

### Get Project By ID
GET {{baseUrl}}/projects/{{projectId}}

### Delete Project
DELETE {{baseUrl}}/projects/{{projectId}}
