@baseUrl = http://localhost:3333/api/v1
@authToken = paste-your-auth-token-here

### Current user
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

### Queries dashboard
GET {{baseUrl}}/queries/dashboard
Authorization: Bearer {{authToken}}

### Queries list
GET {{baseUrl}}/queries
Authorization: Bearer {{authToken}}

### Get trace by ID
GET {{baseUrl}}/traces/00000000000000000000000000000001
Authorization: Bearer {{authToken}}

### Search telemetry data
GET {{baseUrl}}/search?httpMethod=GET&dbName=my_database&dbTable=users&type=HTTP
Authorization: Bearer {{authToken}}
