@baseUrl = https://telemetry-telemetry-api.qltz9y.easypanel.host/api/v1
@projectId = {{createProject.response.body.id}}

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZEVtcHJlc2EiOiJhZjhmYjIzNS1lYThmLTQ3MGMtYThmYy1hNzFkYjg3ZDgzNjciLCJpZFVzZXIiOiI4YzczODNjZi1mNTcwLTQ0NzEtODI1Ny1mZDIxOGUxZGQ3YTUiLCJpYXQiOjE3NjM3NjYwNjIsImV4cCI6MTc2NjM1ODA2Mn0.CUuKO1x53HB0VoBtRudDhn0zByho8fjtLuOC8v6b0XY

### Create Project
# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ZORDON API",
  "description": "Descrição do projeto de teste",
  "enviroment": "production",
  "languageOrFramework": "Node.js"
}

### List Projects
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}

### Get Project By ID
GET {{baseUrl}}/projects/{{projectId}}

### Delete Project
DELETE {{baseUrl}}/projects/{{projectId}}
