@baseUrl = http://localhost:3333/api/v1
@authToken = paste-your-auth-token-here
@projectId = {{createProject.response.body.id}}

### Create Project
# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Example API",
  "description": "Example project",
  "enviroment": "production",
  "languageOrFramework": "Node.js"
}

### Update Project
# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Example API",
  "description": "Updated example project",
  "enviroment": "production",
  "languageOrFramework": "Node.js",
  "token": "proj_example_token",
  "redactionFields": ["token", "authorization"]
}

### List Projects
GET {{baseUrl}}/projects
Authorization: Bearer {{authToken}}

### Get Project By ID
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{authToken}}

### Delete Project
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{authToken}}
