@baseUrl = http://localhost:3333/api/v1
@projectId = {{createProject.response.body.id}}

@token=

### Create Project
# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ZORDON API",
  "description": "Descrição do projeto de teste",
  "enviroment": "production",
  "languageOrFramework": "Node.js"
}

### Update Project
# @name update
PUT {{baseUrl}}/projects/2be5f4f2-2c3a-4bd8-bce1-7140762f0634
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Zordon",
    "description": "Default project created upon user registration",
    "enviroment": "production",
    "languageOrFramework": "unknown",
    "token": "proj_5creaaibv1-y46esh-l4c-xrpc4bw2ahr16fd3v22aea21ctfc3f4-o6cn",
    "redactionFields": [
        "token",
        "authorization"
    ]
}

### List Projects
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}

### Get Project By ID
GET {{baseUrl}}/projects/{{projectId}}

### Delete Project
DELETE {{baseUrl}}/projects/{{projectId}}
